#!/bin/bash -e
set -o pipefail

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PYTHONUNBUFFERED=1

ARM_IMAGE_OFFER='WindowsServer'
ARM_IMAGE_PUBLISHER='MicrosoftWindowsServer'
ARM_IMAGE_SKU='2016-Datacenter'
ARM_MANAGED_IMAGE_NAME='win2016vs2015'

echo ARM_IMAGE_OFFER="$ARM_IMAGE_OFFER"
echo ARM_IMAGE_PUBLISHER="$ARM_IMAGE_PUBLISHER"
echo ARM_IMAGE_SKU="$ARM_IMAGE_SKU"
echo ARM_MANAGED_IMAGE_NAME="$ARM_MANAGED_IMAGE_NAME"
export ARM_IMAGE_OFFER
export ARM_IMAGE_PUBLISHER
export ARM_IMAGE_SKU
export ARM_MANAGED_IMAGE_NAME
packer build -force -only=azure-arm packer.json
